(() => {
  const nested = /\/(services|projects)\//.test(location.pathname);
  const base = nested ? '../' : '';
  const file = location.pathname.split('/').pop() || 'index.html';
  const links = [['index.html','Home'],['about.html','Company'],['services.html','Solutions'],['projects.html','Projects'],['fleet.html','Fleet'],['hse.html','HSE'],['gallery.html','Gallery'],['contact.html','Contact']];
  const header = document.querySelector('.header');
  if (header) header.innerHTML = '<a class="logo" href="'+base+'index.html" aria-label="OSS home"><img src="'+base+'assets/oss-logo.png" alt="OSS Offshore Support Services"></a><button class="menu" aria-label="Open menu" aria-expanded="false"><i></i><i></i><i></i></button><nav class="nav" aria-label="Main navigation">'+links.map(([href,label])=>'<a class="'+(file===href?'active':'')+'" href="'+base+href+'">'+label+'</a>').join('')+'</nav><div class="head-actions"><a class="head-phone" href="tel:+971502606292">+971 50 260 6292</a><a class="enquire" href="'+base+'contact.html#rfq">Enquire</a></div>';
  const footer = document.querySelector('.footer');
  if (footer) footer.innerHTML = '<div class="wrap"><div class="footer-grid"><div><img class="footer-logo" src="'+base+'assets/oss-logo.png" alt="OSS"><p>Integrated offshore, marine and industrial support from Abu Dhabi.</p></div><div><h3>Company</h3><a href="'+base+'about.html">Company</a><a href="'+base+'projects.html">Projects</a><a href="'+base+'hse.html">HSE & Quality</a></div><div><h3>Solutions</h3><a href="'+base+'services/vessel-charter.html">Vessel charter</a><a href="'+base+'services/ship-repair.html">Ship repair</a><a href="'+base+'services/fabrication.html">Fabrication</a><a href="'+base+'fleet.html">Fleet & equipment</a></div><div><h3>Contact</h3><p>MW2, Mussafah Industrial City<br>Abu Dhabi, UAE</p><a href="tel:+971502606292">+971 50 260 6292</a><a href="mailto:commercial@offshoresupportservices.ae">commercial@offshoresupportservices.ae</a></div></div><div class="footer-bottom"><p>© <span data-year></span> OSS Marine Services LLC</p><div><a href="'+base+'privacy.html">Privacy</a><a href="'+base+'terms.html">Terms</a></div></div></div>';
  document.querySelectorAll('[data-year]').forEach(el=>el.textContent=new Date().getFullYear());
  const menu=document.querySelector('.menu'),nav=document.querySelector('.nav');
  menu?.addEventListener('click',()=>{const open=nav.classList.toggle('open');document.body.classList.toggle('menu-open',open);menu.setAttribute('aria-expanded',String(open));});
  nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');document.body.classList.remove('menu-open');}));
  const siteHeader=document.querySelector('.site-header');
  const headerState=()=>siteHeader?.classList.toggle('fixed',scrollY>30);
  addEventListener('scroll',headerState,{passive:true});headerState();
  const cfg=window.OSS_CONFIG||{};
  async function sb(path,opts={}){if(!cfg.supabaseUrl||!cfg.supabaseAnonKey)return null;return fetch(cfg.supabaseUrl+'/rest/v1/'+path,{...opts,headers:{apikey:cfg.supabaseAnonKey,Authorization:'Bearer '+cfg.supabaseAnonKey,'Content-Type':'application/json',...(opts.headers||{})}})}
  const form=document.getElementById('rfq-form'),status=document.getElementById('form-status');
  form?.addEventListener('submit',async e=>{e.preventDefault();if(!form.checkValidity()){form.reportValidity();return}const btn=form.querySelector('button[type=submit]');const data=Object.fromEntries(new FormData(form).entries());if(data.website)return;delete data.website;delete data.consent;data.source='website';data.page=location.pathname;data.status='new';btn.disabled=true;btn.textContent='Sending…';status.textContent='';try{const res=await sb('website_inquiries',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(data)});if(!res?.ok)throw Error('submit');form.reset();status.textContent='Thank you. Your enquiry has been submitted.'}catch(err){status.textContent='Submission failed. Please email commercial@offshoresupportservices.ae or call +971 50 260 6292.'}finally{btn.disabled=false;btn.textContent='Submit enquiry'}});
})();