const cfg=window.OSS_CONFIG||{}; const loginView=document.querySelector('#login-view'), dash=document.querySelector('#dashboard'), panel=document.querySelector('#panel'); let client=null,currentTab='inquiries';
if(cfg.supabaseUrl&&cfg.supabaseAnonKey&&window.supabase) client=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);
const esc=(v='')=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function boot(){if(!client){document.querySelector('#login-status').textContent='Add Supabase URL and anon key to ../config.js first.';return}const {data}=await client.auth.getSession(); if(data.session) showDash(data.session.user);}
function showDash(user){loginView.classList.add('hidden');dash.classList.remove('hidden');document.querySelector('#user-email').textContent=user.email;loadTab(currentTab)}
document.querySelector('#login-form').addEventListener('submit',async e=>{e.preventDefault();if(!client)return;const status=document.querySelector('#login-status');status.textContent='Signing in…';const {data,error}=await client.auth.signInWithPassword({email:document.querySelector('#login-email').value,password:document.querySelector('#login-password').value});if(error){status.textContent=error.message;return}status.textContent='';showDash(data.user)});
document.querySelector('#logout').addEventListener('click',async()=>{await client?.auth.signOut();location.reload()});document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentTab=b.dataset.tab;loadTab(currentTab)}));
async function loadTab(tab){panel.innerHTML='<p>Loading…</p>';if(tab==='inquiries')return loadInquiries();if(tab==='projects')return loadCrud('website_projects','Projects',['title','category','summary','cover_image_url','sort_order','published']);if(tab==='gallery')return loadCrud('website_gallery','Gallery',['caption','image_url','sort_order','published']);if(tab==='equipment')return loadCrud('website_equipment','Equipment',['name','category','summary','availability_note','sort_order','published'])}
async function loadInquiries(){const {data,error}=await client.from('website_inquiries').select('*').order('created_at',{ascending:false}).limit(100);if(error){panel.innerHTML=`<p class="error">${esc(error.message)}</p>`;return}panel.innerHTML=`<div class="toolbar"><h2>Website inquiries</h2><span class="muted">Latest 100</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Date</th><th>Contact</th><th>Service</th><th>Requirement</th><th>Status</th></tr></thead><tbody>${data.map(x=>`<tr><td>${esc(new Date(x.created_at).toLocaleString())}</td><td><strong>${esc(x.name)}</strong><br>${esc(x.company||'')}<br><a href="mailto:${esc(x.email)}">${esc(x.email)}</a><br>${esc(x.phone||'')}</td><td>${esc(x.service||'—')}<br><span class="muted">${esc(x.project_location||'')}</span></td><td>${esc(x.message||'')}</td><td><span class="badge">${esc(x.status||'new')}</span></td></tr>`).join('')}</tbody></table></div>`}
async function loadCrud(table,title,fields){const {data,error}=await client.from(table).select('*').order('sort_order',{ascending:true}).limit(100);if(error){panel.innerHTML=`<p class="error">${esc(error.message)}</p>`;return}panel.innerHTML=`<div class="toolbar"><h2>${title}</h2><button id="add-record">Add record</button></div><div id="editor-slot"></div><div class="table-wrap"><table class="data-table"><thead><tr>${fields.map(f=>`<th>${f}</th>`).join('')}<th></th></tr></thead><tbody>${data.map(r=>`<tr>${fields.map(f=>`<td>${f==='published'?esc(String(r[f])):esc(r[f]||'')}</td>`).join('')}<td><button class="edit" data-id="${r.id}">Edit</button></td></tr>`).join('')}</tbody></table></div>`;document.querySelector('#add-record').onclick=()=>showEditor(table,fields,{});document.querySelectorAll('.edit').forEach(b=>b.onclick=()=>showEditor(table,fields,data.find(x=>String(x.id)===b.dataset.id)))}
function showEditor(table,fields,row){const slot=document.querySelector('#editor-slot');slot.innerHTML=`<form class="editor" id="editor-form">${fields.map(f=>f==='published'?`<label class="check full"><input type="checkbox" name="${f}" ${row[f]?'checked':''}> Published</label>`:`<label class="${['summary','availability_note'].includes(f)?'full':''}">${f}<${['summary','availability_note'].includes(f)?'textarea':'input'} name="${f}" ${f==='sort_order'?'type="number"':''}>${['summary','availability_note'].includes(f)?esc(row[f]||''):''}${['summary','availability_note'].includes(f)?`</textarea>`:''}</label>`).join('')}<div class="actions"><button>Save</button><button type="button" id="cancel">Cancel</button>${row.id?'<button type="button" id="delete">Delete</button>':''}</div></form>`;fields.forEach(f=>{if(['published','summary','availability_note'].includes(f))return;const el=slot.querySelector(`[name="${f}"]`);if(el)el.value=row[f]??''});slot.querySelector('#cancel').onclick=()=>slot.innerHTML='';slot.querySelector('#editor-form').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),payload={};fields.forEach(f=>payload[f]=f==='published'?e.currentTarget.elements[f].checked:(f==='sort_order'?Number(fd.get(f)||0):fd.get(f)));let q=row.id?client.from(table).update(payload).eq('id',row.id):client.from(table).insert(payload);const {error}=await q;if(error)return alert(error.message);loadCrud(table,table.replace('website_',''),fields)};if(row.id)slot.querySelector('#delete').onclick=async()=>{if(!confirm('Delete this record?'))return;const {error}=await client.from(table).delete().eq('id',row.id);if(error)return alert(error.message);loadCrud(table,table.replace('website_',''),fields)}}
boot();